title: ğŸ•Šï¸ FlyPose: Towards Robust Human Pose Estimation From Aerial Views
description: Hassaan Farooq, Marvin Brenner, Peter StÃ¼tz
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
